version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/raba/
      POSTGRES_PASSWORD: password

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  web:
    build: .
    volumes:
      - .:/usr/src/raba
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
