version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/raba/
      POSTGRES_PASSWORD: password

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./tmp/redis:/data

  # https://github.com/bitnami/containers/tree/main/bitnami/kafka
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    volumes:
      - ./tmp/zookeeper:/bitnami/zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # https://github.com/bitnami/containers/tree/main/bitnami/kafka
  kafka:
    image: 'bitnami/kafka:latest'
    volumes:
      - ./tmp/kafka:/bitnami/kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  migrate:
    build: .
    volumes:
      - .:/usr/src/raba
    command: ["migrate"]
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      - db
      - redis

  web:
    build: .
    volumes:
      - .:/usr/src/raba
    command: ["server"]
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    volumes:
      - .:/usr/src/raba
      - /usr/src/raba/tmp
    command: ["sidekiq"]
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      - db
      - redis
